# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atlaspolicymgr/v1/atlas_policy_command_response.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n5atlaspolicymgr/v1/atlas_policy_command_response.proto\x12\x11\x61tlaspolicymgr.v1"\xf3\x04\n\x1a\x41tlasPolicyCommandResponse\x12T\n\x07headers\x18\x01 \x03(\x0b\x32:.atlaspolicymgr.v1.AtlasPolicyCommandResponse.HeadersEntryR\x07headers\x12\x1b\n\tmime_type\x18\x02 \x01(\tR\x08mimeType\x12U\n\toperation\x18\x03 \x01(\x0e\x32\x37.atlaspolicymgr.v1.AtlasPolicyCommandResponse.OperationR\toperation\x12\x18\n\x07payload\x18\x04 \x01(\x0cR\x07payload\x1a:\n\x0cHeadersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01"\xb4\x02\n\tOperation\x12\x19\n\x15OPERATION_UNSPECIFIED\x10\x00\x12#\n\x1fOPERATION_PROTECTION_JOB_CREATE\x10\x01\x12#\n\x1fOPERATION_PROTECTION_JOB_DELETE\x10\x02\x12&\n"OPERATION_PROTECTION_POLICY_UPDATE\x10\x03\x12-\n)OPERATION_PROTECTION_JOB_EXECUTION_UPDATE\x10\x04\x12$\n OPERATION_PROTECTION_JOB_SUSPEND\x10\x05\x12#\n\x1fOPERATION_PROTECTION_JOB_RESUME\x10\x06\x12 \n\x1cOPERATION_PROTECTION_JOB_RUN\x10\x07\x42%Z#atlaspolicymgr/v1;atlaspolicymgr_v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "atlaspolicymgr.v1.atlas_policy_command_response_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z#atlaspolicymgr/v1;atlaspolicymgr_v1"
    _globals["_ATLASPOLICYCOMMANDRESPONSE_HEADERSENTRY"]._options = None
    _globals["_ATLASPOLICYCOMMANDRESPONSE_HEADERSENTRY"]._serialized_options = b"8\001"
    _globals["_ATLASPOLICYCOMMANDRESPONSE"]._serialized_start = 77
    _globals["_ATLASPOLICYCOMMANDRESPONSE"]._serialized_end = 704
    _globals["_ATLASPOLICYCOMMANDRESPONSE_HEADERSENTRY"]._serialized_start = 335
    _globals["_ATLASPOLICYCOMMANDRESPONSE_HEADERSENTRY"]._serialized_end = 393
    _globals["_ATLASPOLICYCOMMANDRESPONSE_OPERATION"]._serialized_start = 396
    _globals["_ATLASPOLICYCOMMANDRESPONSE_OPERATION"]._serialized_end = 704
# @@protoc_insertion_point(module_scope)
