# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lib.platform.kafka.protobuf.cadence.api.v1 import common_pb2 as uber_dot_cadence_dot_api_dot_v1_dot_common__pb2
from lib.platform.kafka.protobuf.cadence.api.v1 import workflow_pb2 as uber_dot_cadence_dot_api_dot_v1_dot_workflow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fuber/cadence/api/v1/query.proto\x12\x13uber.cadence.api.v1\x1a uber/cadence/api/v1/common.proto\x1a\"uber/cadence/api/v1/workflow.proto\"U\n\rWorkflowQuery\x12\x12\n\nquery_type\x18\x01 \x01(\t\x12\x30\n\nquery_args\x18\x02 \x01(\x0b\x32\x1c.uber.cadence.api.v1.Payload\"\x95\x01\n\x13WorkflowQueryResult\x12\x39\n\x0bresult_type\x18\x01 \x01(\x0e\x32$.uber.cadence.api.v1.QueryResultType\x12,\n\x06\x61nswer\x18\x02 \x01(\x0b\x32\x1c.uber.cadence.api.v1.Payload\x12\x15\n\rerror_message\x18\x03 \x01(\t\"X\n\rQueryRejected\x12G\n\x0c\x63lose_status\x18\x01 \x01(\x0e\x32\x31.uber.cadence.api.v1.WorkflowExecutionCloseStatus*n\n\x0fQueryResultType\x12\x1d\n\x19QUERY_RESULT_TYPE_INVALID\x10\x00\x12\x1e\n\x1aQUERY_RESULT_TYPE_ANSWERED\x10\x01\x12\x1c\n\x18QUERY_RESULT_TYPE_FAILED\x10\x02*\x91\x01\n\x14QueryRejectCondition\x12\"\n\x1eQUERY_REJECT_CONDITION_INVALID\x10\x00\x12#\n\x1fQUERY_REJECT_CONDITION_NOT_OPEN\x10\x01\x12\x30\n,QUERY_REJECT_CONDITION_NOT_COMPLETED_CLEANLY\x10\x02*\x86\x01\n\x15QueryConsistencyLevel\x12#\n\x1fQUERY_CONSISTENCY_LEVEL_INVALID\x10\x00\x12$\n QUERY_CONSISTENCY_LEVEL_EVENTUAL\x10\x01\x12\"\n\x1eQUERY_CONSISTENCY_LEVEL_STRONG\x10\x02\x42Z\n\x17\x63om.uber.cadence.api.v1B\nQueryProtoP\x01Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber.cadence.api.v1.query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.uber.cadence.api.v1B\nQueryProtoP\001Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1'
  _QUERYRESULTTYPE._serialized_start=455
  _QUERYRESULTTYPE._serialized_end=565
  _QUERYREJECTCONDITION._serialized_start=568
  _QUERYREJECTCONDITION._serialized_end=713
  _QUERYCONSISTENCYLEVEL._serialized_start=716
  _QUERYCONSISTENCYLEVEL._serialized_end=850
  _WORKFLOWQUERY._serialized_start=126
  _WORKFLOWQUERY._serialized_end=211
  _WORKFLOWQUERYRESULT._serialized_start=214
  _WORKFLOWQUERYRESULT._serialized_end=363
  _QUERYREJECTED._serialized_start=365
  _QUERYREJECTED._serialized_end=453
# @@protoc_insertion_point(module_scope)
