# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/tasklist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"uber/cadence/api/v1/tasklist.proto\x12\x13uber.cadence.api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"I\n\x08TaskList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12/\n\x04kind\x18\x02 \x01(\x0e\x32!.uber.cadence.api.v1.TaskListKind\"N\n\x10TaskListMetadata\x12:\n\x14max_tasks_per_second\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"A\n\x19TaskListPartitionMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x0fowner_host_name\x18\x02 \x01(\t\"\xa5\x01\n\x0eTaskListStatus\x12\x1a\n\x12\x62\x61\x63klog_count_hint\x18\x01 \x01(\x03\x12\x12\n\nread_level\x18\x02 \x01(\x03\x12\x11\n\tack_level\x18\x03 \x01(\x03\x12\x17\n\x0frate_per_second\x18\x04 \x01(\x01\x12\x37\n\rtask_id_block\x18\x05 \x01(\x0b\x32 .uber.cadence.api.v1.TaskIDBlock\"/\n\x0bTaskIDBlock\x12\x10\n\x08start_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x65nd_id\x18\x02 \x01(\x03\"m\n\nPollerInfo\x12\x34\n\x10last_access_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x17\n\x0frate_per_second\x18\x03 \x01(\x01\"\x92\x01\n\x19StickyExecutionAttributes\x12\x37\n\x10worker_task_list\x18\x01 \x01(\x0b\x32\x1d.uber.cadence.api.v1.TaskList\x12<\n\x19schedule_to_start_timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration*`\n\x0cTaskListKind\x12\x1a\n\x16TASK_LIST_KIND_INVALID\x10\x00\x12\x19\n\x15TASK_LIST_KIND_NORMAL\x10\x01\x12\x19\n\x15TASK_LIST_KIND_STICKY\x10\x02*d\n\x0cTaskListType\x12\x1a\n\x16TASK_LIST_TYPE_INVALID\x10\x00\x12\x1b\n\x17TASK_LIST_TYPE_DECISION\x10\x01\x12\x1b\n\x17TASK_LIST_TYPE_ACTIVITY\x10\x02\x42]\n\x17\x63om.uber.cadence.api.v1B\rTaskListProtoP\x01Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber.cadence.api.v1.tasklist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.uber.cadence.api.v1B\rTaskListProtoP\001Z1github.com/uber/cadence-idl/go/proto/api/v1;apiv1'
  _TASKLISTKIND._serialized_start=855
  _TASKLISTKIND._serialized_end=951
  _TASKLISTTYPE._serialized_start=953
  _TASKLISTTYPE._serialized_end=1053
  _TASKLIST._serialized_start=156
  _TASKLIST._serialized_end=229
  _TASKLISTMETADATA._serialized_start=231
  _TASKLISTMETADATA._serialized_end=309
  _TASKLISTPARTITIONMETADATA._serialized_start=311
  _TASKLISTPARTITIONMETADATA._serialized_end=376
  _TASKLISTSTATUS._serialized_start=379
  _TASKLISTSTATUS._serialized_end=544
  _TASKIDBLOCK._serialized_start=546
  _TASKIDBLOCK._serialized_end=593
  _POLLERINFO._serialized_start=595
  _POLLERINFO._serialized_end=704
  _STICKYEXECUTIONATTRIBUTES._serialized_start=707
  _STICKYEXECUTIONATTRIBUTES._serialized_end=853
# @@protoc_insertion_point(module_scope)
