apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage-class
provisioner: ebs.csi.aws.com # kubernetes.io/aws-ebs
parameters:
  type: gp3 # gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
