from enum import Enum


class TaskStatus(Enum):
    TASK_STATUS_UNSPECIFIED = "TASK_STATUS_UNSPECIFIED"
    TASK_STATUS_NOTSTARTED = "TASK_STATUS_NOTSTARTED"
    TASK_STATUS_INPROGRESS = "TASK_STATUS_INPROGRESS"
    TASK_STATUS_COMPLETED = "TASK_STATUS_COMPLETED"
    TASK_STATUS_WAITINGONOTHERS = "TASK_STATUS_WAITINGONOTHERS"
    TASK_STATUS_DEFERRED = "TASK_STATUS_DEFERRED"


class EventStatusResponse(Enum):
    NONE = "none"
    ORGANIZER = "organizer"
    TENTATIVELY_ACCEPTED = "tentativelyAccepted"
    ACCEPTED = "accepted"
    DECLINED = "declined"
    NOT_RESPONSED = "notResponded"
