from enum import Enum


class AtlasPolicyOperations(Enum):
    UNSPECIFIED = "OPERATION_UNSPECIFIED"
    PROTECTION_JOB_CREATE = "OPERATION_PROTECTION_JOB_CREATE"
    PROTECTION_JOB_DELETE = "OPERATION_PROTECTION_JOB_DELETE"
    PROTECTION_POLICY_UPDATE = "OPERATION_PROTECTION_POLICY_UPDATE"
    PROTECTION_JOB_EXECUTION_UPDATE = "OPERATION_PROTECTION_JOB_EXECUTION_UPDATE"
    PROTECTION_JOB_SUSPEND = "OPERATION_PROTECTION_JOB_SUSPEND"
    PROTECTION_JOB_ACCT_SUSPEND = "OPERATION_PROTECTION_JOB_ACCT_SUSPENDED"
    PROTECTION_JOB_RESUME = "OPERATION_PROTECTION_JOB_RESUME"
    PROTECTION_JOB_RUN = "OPERATION_PROTECTION_JOB_RUN"
