from enum import Enum


class InvoicingModel(Enum):
    INVOICING_MODEL_UNSPECIFIED = "INVOICING_MODEL_UNSPECIFIED"
    INVOICING_MODEL_EVAL = "INVOICING_MODEL_EVAL"
    INVOICING_MODEL_CO = "INVOICING_MODEL_CO"
    INVOICING_MODEL_UP = "INVOICING_MODEL_UP"
    INVOICING_MODEL_CO_SU = "INVOICING_MODEL_CO_SU"
    INVOICING_MODEL_CL_PR_DR = "INVOICING_MODEL_CL_PR_DR"
    INVOICING_MODEL_SU = "INVOICING_MODEL_SU"
