from enum import Enum


class SubclassifierProperties(Enum):
    BASIC_AUTH = "BASIC_AUTH"
    OAUTH_CLIENT = "OAUTH_CLIENT"
    BEARER_AUTH = "BEARER_AUTH"
    AZURE_SPCLIENT = "AZURE_SPCLIENT"
    SSH_KEYPAIR = "SSH_KEYPAIR"
    CERTIFICATE = "CERTIFICATE"
    GENERIC = "GENERIC"
    JSON_WEB_TOKEN = "JSON_WEB_TOKEN"
    PASSWORD = "PASSWORD"
    PRIVATE_KEY = "PRIVATE_KEY"
