# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/admin/v1/cluster.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#uber/cadence/admin/v1/cluster.proto\x12\x15uber.cadence.admin.v1\"\x1c\n\x08HostInfo\x12\x10\n\x08identity\x18\x01 \x01(\t\"`\n\x08RingInfo\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x14\n\x0cmember_count\x18\x02 \x01(\x05\x12\x30\n\x07members\x18\x03 \x03(\x0b\x32\x1f.uber.cadence.admin.v1.HostInfo\"\x92\x01\n\x0eMembershipInfo\x12\x35\n\x0c\x63urrent_host\x18\x01 \x01(\x0b\x32\x1f.uber.cadence.admin.v1.HostInfo\x12\x19\n\x11reachable_members\x18\x02 \x03(\t\x12.\n\x05rings\x18\x03 \x03(\x0b\x32\x1f.uber.cadence.admin.v1.RingInfo\"]\n\x0f\x44omainCacheInfo\x12#\n\x1bnum_of_items_in_cache_by_id\x18\x01 \x01(\x03\x12%\n\x1dnum_of_items_in_cache_by_name\x18\x02 \x01(\x03\"0\n\x12PersistenceSetting\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"2\n\x12PersistenceFeature\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"\x9c\x01\n\x0fPersistenceInfo\x12\x0f\n\x07\x62\x61\x63kend\x18\x01 \x01(\t\x12;\n\x08settings\x18\x02 \x03(\x0b\x32).uber.cadence.admin.v1.PersistenceSetting\x12;\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32).uber.cadence.admin.v1.PersistenceFeatureB7Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber.cadence.admin.v1.cluster_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1'
  _HOSTINFO._serialized_start=62
  _HOSTINFO._serialized_end=90
  _RINGINFO._serialized_start=92
  _RINGINFO._serialized_end=188
  _MEMBERSHIPINFO._serialized_start=191
  _MEMBERSHIPINFO._serialized_end=337
  _DOMAINCACHEINFO._serialized_start=339
  _DOMAINCACHEINFO._serialized_end=432
  _PERSISTENCESETTING._serialized_start=434
  _PERSISTENCESETTING._serialized_end=482
  _PERSISTENCEFEATURE._serialized_start=484
  _PERSISTENCEFEATURE._serialized_end=534
  _PERSISTENCEINFO._serialized_start=537
  _PERSISTENCEINFO._serialized_end=693
# @@protoc_insertion_point(module_scope)
