# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/admin/v1/history.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#uber/cadence/admin/v1/history.proto\x12\x15uber.cadence.admin.v1\"7\n\x12VersionHistoryItem\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x03\x12\x0f\n\x07version\x18\x02 \x01(\x03\"`\n\x0eVersionHistory\x12\x14\n\x0c\x62ranch_token\x18\x01 \x01(\x0c\x12\x38\n\x05items\x18\x02 \x03(\x0b\x32).uber.cadence.admin.v1.VersionHistoryItemB7Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uber.cadence.admin.v1.history_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/uber/cadence-idl/go/proto/admin/v1;adminv1'
  _VERSIONHISTORYITEM._serialized_start=62
  _VERSIONHISTORYITEM._serialized_end=117
  _VERSIONHISTORY._serialized_start=119
  _VERSIONHISTORY._serialized_end=215
# @@protoc_insertion_point(module_scope)
