# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from uber.cadence.admin.v1 import service_pb2 as uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2


class AdminAPIStub(object):
    """AdminAPI provides advanced APIs for debugging and analysis with admin privilege.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DescribeWorkflowExecution = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DescribeWorkflowExecution',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.FromString,
                )
        self.DescribeHistoryHost = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DescribeHistoryHost',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostResponse.FromString,
                )
        self.DescribeShardDistribution = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DescribeShardDistribution',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionResponse.FromString,
                )
        self.CloseShard = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/CloseShard',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardResponse.FromString,
                )
        self.RemoveTask = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/RemoveTask',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskResponse.FromString,
                )
        self.ResetQueue = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/ResetQueue',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueResponse.FromString,
                )
        self.DescribeQueue = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DescribeQueue',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueResponse.FromString,
                )
        self.GetWorkflowExecutionRawHistoryV2 = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetWorkflowExecutionRawHistoryV2',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Request.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Response.FromString,
                )
        self.GetReplicationMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetReplicationMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesResponse.FromString,
                )
        self.GetDLQReplicationMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetDLQReplicationMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesResponse.FromString,
                )
        self.GetDomainReplicationMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetDomainReplicationMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesResponse.FromString,
                )
        self.ReapplyEvents = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/ReapplyEvents',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsResponse.FromString,
                )
        self.AddSearchAttribute = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/AddSearchAttribute',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeResponse.FromString,
                )
        self.DescribeCluster = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DescribeCluster',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterResponse.FromString,
                )
        self.CountDLQMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/CountDLQMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesResponse.FromString,
                )
        self.ReadDLQMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/ReadDLQMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesResponse.FromString,
                )
        self.PurgeDLQMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/PurgeDLQMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesResponse.FromString,
                )
        self.MergeDLQMessages = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/MergeDLQMessages',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesResponse.FromString,
                )
        self.RefreshWorkflowTasks = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/RefreshWorkflowTasks',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksResponse.FromString,
                )
        self.ResendReplicationTasks = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/ResendReplicationTasks',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksResponse.FromString,
                )
        self.GetCrossClusterTasks = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetCrossClusterTasks',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksResponse.FromString,
                )
        self.RespondCrossClusterTasksCompleted = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/RespondCrossClusterTasksCompleted',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedResponse.FromString,
                )
        self.GetDynamicConfig = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/GetDynamicConfig',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigResponse.FromString,
                )
        self.UpdateDynamicConfig = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/UpdateDynamicConfig',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigResponse.FromString,
                )
        self.RestoreDynamicConfig = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/RestoreDynamicConfig',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigResponse.FromString,
                )
        self.ListDynamicConfig = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/ListDynamicConfig',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigResponse.FromString,
                )
        self.DeleteWorkflow = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/DeleteWorkflow',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowResponse.FromString,
                )
        self.MaintainCorruptWorkflow = channel.unary_unary(
                '/uber.cadence.admin.v1.AdminAPI/MaintainCorruptWorkflow',
                request_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowRequest.SerializeToString,
                response_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowResponse.FromString,
                )


class AdminAPIServicer(object):
    """AdminAPI provides advanced APIs for debugging and analysis with admin privilege.
    """

    def DescribeWorkflowExecution(self, request, context):
        """DescribeWorkflowExecution returns information about the internal states of workflow execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeHistoryHost(self, request, context):
        """DescribeHistoryHost returns information about the internal states of a history host.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeShardDistribution(self, request, context):
        """DescribeShardDistribution returns information about shard distribution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseShard(self, request, context):
        """CloseShard closes shard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTask(self, request, context):
        """RemoveTask removes task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetQueue(self, request, context):
        """ResetQueue resets queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeQueue(self, request, context):
        """DescribeQueue describes queue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowExecutionRawHistoryV2(self, request, context):
        """Returns the raw history of specified workflow execution.
        It fails with 'EntityNotExistError' if specified workflow execution in unknown to the service.
        StartEventId defines the beginning of the event to fetch. The first event is inclusive.
        EndEventId and EndEventVersion defines the end of the event to fetch. The end event is exclusive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicationMessages(self, request, context):
        """GetReplicationMessages returns new replication tasks since the read level provided in the token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDLQReplicationMessages(self, request, context):
        """GetDLQReplicationMessages return replication messages based on DLQ info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDomainReplicationMessages(self, request, context):
        """GetDomainReplicationMessages returns new domain replication tasks since last retrieved task id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReapplyEvents(self, request, context):
        """ReapplyEvents applies stale events to the current workflow and current run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSearchAttribute(self, request, context):
        """AddSearchAttribute whitelist search attribute in request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCluster(self, request, context):
        """DescribeCluster returns information about Cadence cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountDLQMessages(self, request, context):
        """CountDLQMessages returns message count in DLQ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadDLQMessages(self, request, context):
        """ReadDLQMessages returns messages from DLQ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeDLQMessages(self, request, context):
        """PurgeDLQMessages purges messages from DLQ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeDLQMessages(self, request, context):
        """MergeDLQMessages merges messages from DLQ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshWorkflowTasks(self, request, context):
        """RefreshWorkflowTasks refreshes all tasks of a workflow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendReplicationTasks(self, request, context):
        """ResendReplicationTasks requests replication tasks from remote cluster and apply tasks to current cluster.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossClusterTasks(self, request, context):
        """GetCrossClusterTasks return cross cluster tasks based on cluster name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondCrossClusterTasksCompleted(self, request, context):
        """RespondCrossClusterTasksCompleted responds the result of processing cross cluster tasks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDynamicConfig(self, request, context):
        """GetDynamicConfig returns values associated with a specified dynamic config parameter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDynamicConfig(self, request, context):
        """UpdateDynamicConfig is used to update one or more values associated with a specified dynamic config parameter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreDynamicConfig(self, request, context):
        """RestoreDynamicConfig is used to remove one or all values associated with a specified dynamic config parameter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDynamicConfig(self, request, context):
        """ListDynamicConfig returns all dynamic config parameters and associated values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkflow(self, request, context):
        """DeleteWorkflow is used to delete a workflow with given domainName, workflowID and runID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaintainCorruptWorkflow(self, request, context):
        """MaintainCorruptWorkflow deletes a workflow if its history is corrupt due to underlying DB issues (e.g. Cassandra resurrections)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DescribeWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeWorkflowExecution,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.SerializeToString,
            ),
            'DescribeHistoryHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeHistoryHost,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostResponse.SerializeToString,
            ),
            'DescribeShardDistribution': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeShardDistribution,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionResponse.SerializeToString,
            ),
            'CloseShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseShard,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardResponse.SerializeToString,
            ),
            'RemoveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTask,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskResponse.SerializeToString,
            ),
            'ResetQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetQueue,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueResponse.SerializeToString,
            ),
            'DescribeQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeQueue,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueResponse.SerializeToString,
            ),
            'GetWorkflowExecutionRawHistoryV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowExecutionRawHistoryV2,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Request.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Response.SerializeToString,
            ),
            'GetReplicationMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesResponse.SerializeToString,
            ),
            'GetDLQReplicationMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDLQReplicationMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesResponse.SerializeToString,
            ),
            'GetDomainReplicationMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomainReplicationMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesResponse.SerializeToString,
            ),
            'ReapplyEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ReapplyEvents,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsResponse.SerializeToString,
            ),
            'AddSearchAttribute': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSearchAttribute,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeResponse.SerializeToString,
            ),
            'DescribeCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCluster,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterResponse.SerializeToString,
            ),
            'CountDLQMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.CountDLQMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesResponse.SerializeToString,
            ),
            'ReadDLQMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadDLQMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesResponse.SerializeToString,
            ),
            'PurgeDLQMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeDLQMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesResponse.SerializeToString,
            ),
            'MergeDLQMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeDLQMessages,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesResponse.SerializeToString,
            ),
            'RefreshWorkflowTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshWorkflowTasks,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksResponse.SerializeToString,
            ),
            'ResendReplicationTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendReplicationTasks,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksResponse.SerializeToString,
            ),
            'GetCrossClusterTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossClusterTasks,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksResponse.SerializeToString,
            ),
            'RespondCrossClusterTasksCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondCrossClusterTasksCompleted,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedResponse.SerializeToString,
            ),
            'GetDynamicConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDynamicConfig,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigResponse.SerializeToString,
            ),
            'UpdateDynamicConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDynamicConfig,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigResponse.SerializeToString,
            ),
            'RestoreDynamicConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreDynamicConfig,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigResponse.SerializeToString,
            ),
            'ListDynamicConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDynamicConfig,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigResponse.SerializeToString,
            ),
            'DeleteWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkflow,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowResponse.SerializeToString,
            ),
            'MaintainCorruptWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.MaintainCorruptWorkflow,
                    request_deserializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowRequest.FromString,
                    response_serializer=uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uber.cadence.admin.v1.AdminAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminAPI(object):
    """AdminAPI provides advanced APIs for debugging and analysis with admin privilege.
    """

    @staticmethod
    def DescribeWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DescribeWorkflowExecution',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeHistoryHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DescribeHistoryHost',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeHistoryHostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeShardDistribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DescribeShardDistribution',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeShardDistributionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/CloseShard',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CloseShardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/RemoveTask',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RemoveTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/ResetQueue',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResetQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DescribeQueue',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeQueueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkflowExecutionRawHistoryV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetWorkflowExecutionRawHistoryV2',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Request.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetWorkflowExecutionRawHistoryV2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicationMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetReplicationMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetReplicationMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDLQReplicationMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetDLQReplicationMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDLQReplicationMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDomainReplicationMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetDomainReplicationMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDomainReplicationMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReapplyEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/ReapplyEvents',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReapplyEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddSearchAttribute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/AddSearchAttribute',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.AddSearchAttributeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DescribeCluster',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DescribeClusterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CountDLQMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/CountDLQMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.CountDLQMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadDLQMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/ReadDLQMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ReadDLQMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PurgeDLQMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/PurgeDLQMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.PurgeDLQMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MergeDLQMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/MergeDLQMessages',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MergeDLQMessagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshWorkflowTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/RefreshWorkflowTasks',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RefreshWorkflowTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResendReplicationTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/ResendReplicationTasks',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ResendReplicationTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCrossClusterTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetCrossClusterTasks',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetCrossClusterTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RespondCrossClusterTasksCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/RespondCrossClusterTasksCompleted',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RespondCrossClusterTasksCompletedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDynamicConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/GetDynamicConfig',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.GetDynamicConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDynamicConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/UpdateDynamicConfig',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.UpdateDynamicConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreDynamicConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/RestoreDynamicConfig',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.RestoreDynamicConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDynamicConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/ListDynamicConfig',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.ListDynamicConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/DeleteWorkflow',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.DeleteWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MaintainCorruptWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uber.cadence.admin.v1.AdminAPI/MaintainCorruptWorkflow',
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowRequest.SerializeToString,
            uber_dot_cadence_dot_admin_dot_v1_dot_service__pb2.MaintainCorruptWorkflowResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
