# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csp/cloudaccountmanager/v1/account_use.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .. import validate_pb2 as validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n,csp/cloudaccountmanager/v1/account_use.proto\x12\x1a\x63sp.cloudaccountmanager.v1\x1a\x0evalidate.proto\"\x89\x01\n\x16\x43spAccountUseByService\x12'\n\naccount_id\x18\x01 \x01(\tB\x08\xfa\x42\x05r\x03\xb0\x01\x01R\taccountId\x12*\n\x0cservice_name\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x0bserviceName\x12\x1a\n\tis_in_use\x18\x03 \x01(\x08R\x07isInUseB7Z5csp/cloudaccountmanager/v1;csp_cloudaccountmanager_v1b\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "csp.cloudaccountmanager.v1.account_use_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z5csp/cloudaccountmanager/v1;csp_cloudaccountmanager_v1"
    _CSPACCOUNTUSEBYSERVICE.fields_by_name["account_id"]._options = None
    _CSPACCOUNTUSEBYSERVICE.fields_by_name["account_id"]._serialized_options = b"\372B\005r\003\260\001\001"
    _CSPACCOUNTUSEBYSERVICE.fields_by_name["service_name"]._options = None
    _CSPACCOUNTUSEBYSERVICE.fields_by_name["service_name"]._serialized_options = b"\372B\004r\002\020\001"
    _CSPACCOUNTUSEBYSERVICE._serialized_start = 93
    _CSPACCOUNTUSEBYSERVICE._serialized_end = 230
# @@protoc_insertion_point(module_scope)
