# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csp/dataprotection/v1/backup_actions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .. import validate_pb2 as validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*csp/dataprotection/v1/backup_actions.proto\x12\x15\x63sp.dataprotection.v1\x1a\x0evalidate.proto\"\xb9\x03\n\x15InitiateBackupRequest\x12S\n\x07headers\x18\x01 \x03(\x0b\x32\x39.csp.dataprotection.v1.InitiateBackupRequest.HeadersEntryR\x07headers\x12\x65\n\x0ctrigger_type\x18\x02 \x01(\x0e\x32\x38.csp.dataprotection.v1.InitiateBackupRequest.TriggerTypeB\x08\xfa\x42\x05\x82\x01\x02 \x00R\x0btriggerType\x12*\n\x11payload_mime_type\x18\x03 \x01(\tR\x0fpayloadMimeType\x12\x18\n\x07payload\x18\x04 \x01(\x0cR\x07payload\x1a:\n\x0cHeadersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"b\n\x0bTriggerType\x12\x1c\n\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16TRIGGER_TYPE_SCHEDULED\x10\x01\x12\x19\n\x15TRIGGER_TYPE_ONDEMAND\x10\x02\"a\n\x0eNightlyTrigger\x12\'\n\naccount_id\x18\x01 \x01(\tB\x08\xfa\x42\x05r\x03\xb0\x01\x01R\taccountId\x12&\n\ncsp_region\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\tcspRegionB-Z+csp/dataprotection/v1;csp_dataprotection_v1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csp.dataprotection.v1.backup_actions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z+csp/dataprotection/v1;csp_dataprotection_v1'
  _INITIATEBACKUPREQUEST_HEADERSENTRY._options = None
  _INITIATEBACKUPREQUEST_HEADERSENTRY._serialized_options = b'8\001'
  _INITIATEBACKUPREQUEST.fields_by_name['trigger_type']._options = None
  _INITIATEBACKUPREQUEST.fields_by_name['trigger_type']._serialized_options = b'\372B\005\202\001\002 \000'
  _NIGHTLYTRIGGER.fields_by_name['account_id']._options = None
  _NIGHTLYTRIGGER.fields_by_name['account_id']._serialized_options = b'\372B\005r\003\260\001\001'
  _NIGHTLYTRIGGER.fields_by_name['csp_region']._options = None
  _NIGHTLYTRIGGER.fields_by_name['csp_region']._serialized_options = b'\372B\004r\002\020\001'
  _INITIATEBACKUPREQUEST._serialized_start=86
  _INITIATEBACKUPREQUEST._serialized_end=527
  _INITIATEBACKUPREQUEST_HEADERSENTRY._serialized_start=369
  _INITIATEBACKUPREQUEST_HEADERSENTRY._serialized_end=427
  _INITIATEBACKUPREQUEST_TRIGGERTYPE._serialized_start=429
  _INITIATEBACKUPREQUEST_TRIGGERTYPE._serialized_end=527
  _NIGHTLYTRIGGER._serialized_start=529
  _NIGHTLYTRIGGER._serialized_end=626
# @@protoc_insertion_point(module_scope)
