version: "3.4"
services:
  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./:/src
    env_file: docker.env
    # environment:
    #   - HTTP_PROXY=http://web-proxy.corp.hpecorp.net:8080
    #   - HTTPS_PROXY=http://web-proxy.corp.hpecorp.net:8080
    #   - http_proxy=http://web-proxy.corp.hpecorp.net:8080
    #   - https_proxy=http://web-proxy.corp.hpecorp.net:8080
    #   - no_proxy=127.0.0.1,localhost,.nimblestorage.com,10.0.0.0/8,192.0.0.0/8,172.0.0.0/8,*.vlab.nimblestorage.com,*.cxo.storage.hpecorp.net

    command: run /src/list_protectiongateway.js -e TEST_CONFIG=testconfig.json --insecure-skip-tls-verify  --quiet
    
    # To execute run the below command
    # cd into k6-perf-tests folder <repo>/qa_automation/Atlas-catayst-gw-e2e-api/k6-perf-tests
    # sudo docker-compose -f docker-compose.yml up