# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csp/inventory/v1/account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .. import validate_pb2 as validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x63sp/inventory/v1/account.proto\x12\x10\x63sp.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0evalidate.proto"e\n\x12SyncAccountRequest\x12&\n\nservice_id\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\tserviceId\x12\'\n\naccount_id\x18\x02 \x01(\tB\x08\xfa\x42\x05r\x03\xb0\x01\x01R\taccountId"\xd7\x02\n\x0f\x41\x63\x63ountSyncInfo\x12\'\n\naccount_id\x18\x01 \x01(\tB\x08\xfa\x42\x05r\x03\xb0\x01\x01R\taccountId\x12R\n\x0elast_synced_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x10\xfa\x42\r\xb2\x01\n\x08\x01*\x06\x08\x80\xb3\xbe\x8e\x06R\x0clastSyncedAt\x12\\\n\x10last_sync_status\x18\x03 \x01(\x0e\x32(.csp.inventory.v1.AccountSyncInfo.StatusB\x08\xfa\x42\x05\x82\x01\x02 \x00R\x0elastSyncStatus"i\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x12\n\x0eSTATUS_WARNING\x10\x02\x12\x10\n\x0cSTATUS_ERROR\x10\x03\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x04\x42#Z!csp/inventory/v1;csp_inventory_v1b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "csp.inventory.v1.account_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z!csp/inventory/v1;csp_inventory_v1"
    _SYNCACCOUNTREQUEST.fields_by_name["service_id"]._options = None
    _SYNCACCOUNTREQUEST.fields_by_name["service_id"]._serialized_options = b"\372B\004r\002\020\001"
    _SYNCACCOUNTREQUEST.fields_by_name["account_id"]._options = None
    _SYNCACCOUNTREQUEST.fields_by_name["account_id"]._serialized_options = b"\372B\005r\003\260\001\001"
    _ACCOUNTSYNCINFO.fields_by_name["account_id"]._options = None
    _ACCOUNTSYNCINFO.fields_by_name["account_id"]._serialized_options = b"\372B\005r\003\260\001\001"
    _ACCOUNTSYNCINFO.fields_by_name["last_synced_at"]._options = None
    _ACCOUNTSYNCINFO.fields_by_name[
        "last_synced_at"
    ]._serialized_options = b"\372B\r\262\001\n\010\001*\006\010\200\263\276\216\006"
    _ACCOUNTSYNCINFO.fields_by_name["last_sync_status"]._options = None
    _ACCOUNTSYNCINFO.fields_by_name["last_sync_status"]._serialized_options = b"\372B\005\202\001\002 \000"
    _SYNCACCOUNTREQUEST._serialized_start = 101
    _SYNCACCOUNTREQUEST._serialized_end = 202
    _ACCOUNTSYNCINFO._serialized_start = 205
    _ACCOUNTSYNCINFO._serialized_end = 548
    _ACCOUNTSYNCINFO_STATUS._serialized_start = 443
    _ACCOUNTSYNCINFO_STATUS._serialized_end = 548
# @@protoc_insertion_point(module_scope)
