# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import asset_pb2 as csp_dot_inventory_dot_v1_dot_asset__pb2
from . import (
    protection_group_pb2 as csp_dot_inventory_dot_v1_dot_protection__group__pb2,
)


class InventoryManagerServiceStub(object):
    """
    Inventory Manager synchronous APIs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAsset = channel.unary_unary(
            "/csp.inventory.v1.InventoryManagerService/GetAsset",
            request_serializer=csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetRequest.SerializeToString,
            response_deserializer=csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetResponse.FromString,
        )
        self.LookupAssetByCspID = channel.unary_unary(
            "/csp.inventory.v1.InventoryManagerService/LookupAssetByCspID",
            request_serializer=csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDRequest.SerializeToString,
            response_deserializer=csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDResponse.FromString,
        )
        self.GetProtectionGroup = channel.unary_unary(
            "/csp.inventory.v1.InventoryManagerService/GetProtectionGroup",
            request_serializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupRequest.SerializeToString,
            response_deserializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupResponse.FromString,
        )
        self.ResolveProtectionGroup = channel.unary_unary(
            "/csp.inventory.v1.InventoryManagerService/ResolveProtectionGroup",
            request_serializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupRequest.SerializeToString,
            response_deserializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupResponse.FromString,
        )


class InventoryManagerServiceServicer(object):
    """
    Inventory Manager synchronous APIs.
    """

    def GetAsset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LookupAssetByCspID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProtectionGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResolveProtectionGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InventoryManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetAsset": grpc.unary_unary_rpc_method_handler(
            servicer.GetAsset,
            request_deserializer=csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetRequest.FromString,
            response_serializer=csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetResponse.SerializeToString,
        ),
        "LookupAssetByCspID": grpc.unary_unary_rpc_method_handler(
            servicer.LookupAssetByCspID,
            request_deserializer=csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDRequest.FromString,
            response_serializer=csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDResponse.SerializeToString,
        ),
        "GetProtectionGroup": grpc.unary_unary_rpc_method_handler(
            servicer.GetProtectionGroup,
            request_deserializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupRequest.FromString,
            response_serializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupResponse.SerializeToString,
        ),
        "ResolveProtectionGroup": grpc.unary_unary_rpc_method_handler(
            servicer.ResolveProtectionGroup,
            request_deserializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupRequest.FromString,
            response_serializer=csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "csp.inventory.v1.InventoryManagerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class InventoryManagerService(object):
    """
    Inventory Manager synchronous APIs.
    """

    @staticmethod
    def GetAsset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/csp.inventory.v1.InventoryManagerService/GetAsset",
            csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetRequest.SerializeToString,
            csp_dot_inventory_dot_v1_dot_asset__pb2.GetAssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def LookupAssetByCspID(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/csp.inventory.v1.InventoryManagerService/LookupAssetByCspID",
            csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDRequest.SerializeToString,
            csp_dot_inventory_dot_v1_dot_asset__pb2.LookupAssetByCspIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetProtectionGroup(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/csp.inventory.v1.InventoryManagerService/GetProtectionGroup",
            csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupRequest.SerializeToString,
            csp_dot_inventory_dot_v1_dot_protection__group__pb2.GetProtectionGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ResolveProtectionGroup(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/csp.inventory.v1.InventoryManagerService/ResolveProtectionGroup",
            csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupRequest.SerializeToString,
            csp_dot_inventory_dot_v1_dot_protection__group__pb2.ResolveProtectionGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
