# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csp/inventory/v1/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import asset_pb2 as csp_dot_inventory_dot_v1_dot_asset__pb2
from . import (
    protection_group_pb2 as csp_dot_inventory_dot_v1_dot_protection__group__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x63sp/inventory/v1/service.proto\x12\x10\x63sp.inventory.v1\x1a\x1c\x63sp/inventory/v1/asset.proto\x1a\'csp/inventory/v1/protection_group.proto2\xd3\x03\n\x17InventoryManagerService\x12S\n\x08GetAsset\x12!.csp.inventory.v1.GetAssetRequest\x1a".csp.inventory.v1.GetAssetResponse"\x00\x12q\n\x12LookupAssetByCspID\x12+.csp.inventory.v1.LookupAssetByCspIDRequest\x1a,.csp.inventory.v1.LookupAssetByCspIDResponse"\x00\x12q\n\x12GetProtectionGroup\x12+.csp.inventory.v1.GetProtectionGroupRequest\x1a,.csp.inventory.v1.GetProtectionGroupResponse"\x00\x12}\n\x16ResolveProtectionGroup\x12/.csp.inventory.v1.ResolveProtectionGroupRequest\x1a\x30.csp.inventory.v1.ResolveProtectionGroupResponse"\x00\x42#Z!csp/inventory/v1;csp_inventory_v1b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "csp.inventory.v1.service_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z!csp/inventory/v1;csp_inventory_v1"
    _INVENTORYMANAGERSERVICE._serialized_start = 124
    _INVENTORYMANAGERSERVICE._serialized_end = 591
# @@protoc_insertion_point(module_scope)
